// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package token

import (
	"github.com/tfkhdyt/openmusic-go/config/jwt"
)

// Injectors from wire.go:

func InitializeManager() *Manager {
	config := jwt.NewConfig()
	manager := NewManager(config)
	return manager
}
