// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package song

import (
	song2 "github.com/tfkhdyt/openmusic-go/controller/song"
	"github.com/tfkhdyt/openmusic-go/service/song"
)

// Injectors from wire.go:

func InitializeRouter() *Router {
	service := song.InitializeService()
	controller := song2.NewController(service)
	router := NewRouter(controller)
	return router
}
