// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	auth2 "github.com/tfkhdyt/openmusic-go/controller/auth"
	"github.com/tfkhdyt/openmusic-go/service/auth"
	"github.com/tfkhdyt/openmusic-go/service/user"
	"github.com/tfkhdyt/openmusic-go/tokenize/token"
)

// Injectors from wire.go:

func InitializeRouter() *Router {
	service := auth.InitializeService()
	userService := user.InitializeService()
	manager := token.InitializeManager()
	controller := auth2.NewController(service, userService, manager)
	router := NewRouter(controller)
	return router
}
