// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package album

import (
	"github.com/tfkhdyt/openmusic-go/repository/postgres/album"
)

// Injectors from wire.go:

func InitializeService() *Service {
	repository := album.NewRepository()
	service := NewService(repository)
	return service
}
