// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package playlist

import (
	playlist2 "github.com/tfkhdyt/openmusic-go/controller/playlist"
	"github.com/tfkhdyt/openmusic-go/service/playlist"
)

// Injectors from wire.go:

func InitializeRouter() *Router {
	service := playlist.InitializeService()
	controller := playlist2.NewController(service)
	router := NewRouter(controller)
	return router
}
