// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package playlist

import (
	playlist2 "github.com/tfkhdyt/openmusic-go/controller/playlist"
	playlistsong2 "github.com/tfkhdyt/openmusic-go/controller/playlistsong"
	playlistsongactivity2 "github.com/tfkhdyt/openmusic-go/controller/playlistsongactivity"
	"github.com/tfkhdyt/openmusic-go/service/playlist"
	"github.com/tfkhdyt/openmusic-go/service/playlistsong"
	"github.com/tfkhdyt/openmusic-go/service/playlistsongactivity"
	"github.com/tfkhdyt/openmusic-go/service/song"
)

// Injectors from wire.go:

func InitializeRouter() *Router {
	service := playlist.InitializeService()
	playlistsongactivityService := playlistsongactivity.InitializeService()
	controller := playlist2.NewController(service, playlistsongactivityService)
	playlistsongService := playlistsong.InitializeService()
	songService := song.InitializeService()
	playlistsongController := playlistsong2.NewController(playlistsongService, service, songService, playlistsongactivityService)
	playlistsongactivityController := playlistsongactivity2.NewController(playlistsongactivityService, service)
	router := NewRouter(controller, playlistsongController, playlistsongactivityController)
	return router
}
