// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package collab

import (
	collab2 "github.com/tfkhdyt/openmusic-go/controller/collab"
	"github.com/tfkhdyt/openmusic-go/service/collab"
	"github.com/tfkhdyt/openmusic-go/service/playlist"
	"github.com/tfkhdyt/openmusic-go/service/user"
)

// Injectors from wire.go:

func InitializeRouter() *Router {
	service := collab.InitializeService()
	playlistService := playlist.InitializeService()
	userService := user.InitializeService()
	controller := collab2.NewController(service, playlistService, userService)
	router := NewRouter(controller)
	return router
}
