// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package album

import (
	album2 "github.com/tfkhdyt/openmusic-go/controller/album"
	"github.com/tfkhdyt/openmusic-go/service/album"
	"github.com/tfkhdyt/openmusic-go/service/song"
)

// Injectors from wire.go:

func InitializeRouter() *Router {
	service := album.InitializeService()
	songService := song.InitializeService()
	controller := album2.NewController(service, songService)
	router := NewRouter(controller)
	return router
}
