// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package playlist

import (
	"github.com/tfkhdyt/openmusic-go/repository/postgres/playlist"
	"github.com/tfkhdyt/openmusic-go/service/collab"
)

// Injectors from wire.go:

func InitializeService() *Service {
	repository := playlist.NewRepository()
	service := collab.InitializeService()
	playlistService := NewService(repository, service)
	return playlistService
}
